# Generated by Django 4.0.5 on 2022-08-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemzem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reasonOfFailure',
        ),
        migrations.AddField(
            model_name='order',
            name='customerComment',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='providerComment',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='wasDelivered',
            field=models.BooleanField(default=False),
        ),
    ]
