# Generated by Django 4.0.5 on 2022-07-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemzem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveredAt',
            field=models.DateTimeField(blank=True),
        ),
    ]
