# Generated by Django 4.0.5 on 2022-07-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemzem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
