# Generated by Django 4.0.5 on 2022-06-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemzem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
