# Generated by Django 4.0.5 on 2022-07-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemzem', '0003_alter_customer_email_alter_customer_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
