# Generated by Django 4.0.5 on 2022-07-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemzem', '0004_delete_administrator_delete_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
