# Generated by Django 4.0.5 on 2022-07-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemzem', '0007_remove_provider_first_time_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
