# Generated by Django 4.0.5 on 2022-07-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemzem', '0008_alter_provider_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created',
            field=models.DateField(),
        ),
    ]
