# Generated by Django 4.0.5 on 2022-07-07 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zemzem', '0009_alter_provider_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='isLocked',
            new_name='is_locked',
        ),
        migrations.AddField(
            model_name='provider',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='zemzem.provider')),
                ('phone_number', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('is_potable', models.BooleanField(default=True)),
                ('special_instructions', models.TextField()),
                ('location', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zemzem.customer')),
            ],
        ),
    ]
