name: zemzem
on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: |
          cd backend
          python manage.py migrate
      - name: Run backend tests
        run: |
          cd backend
          python manage.py test zemzem.tests
      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install
      - name: Run frontend tests
        run: |
          cd frontend
          yarn test --maxWorkers=1

#      - name: Lint with flake8
#        run: |
#          pip install flake8
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
